### ISSUE TITLE
HG19

### ISSUE THREAD

**Issue by Pharmacogenetecist** [lmtani/wf-human-mito#13]
Thank you for your previous assistance. I am getting the following when running against HG19.

 nextflow run lmtani/wf-human-mito -r main --alignments "/20220803_BAM/*.ba{i,m}"  --restore_hardclips false --outdir "/DATA/JSTUDY/" --reference "/DATA/HG19/hg19.fa" -profile docker
N E X T F L O W  ~  version 22.04.5
Launching `https://github.com/lmtani/wf-human-mito` [evil_lavoisier] DSL2 - revision: a12bad4102 [main]
executor >  local (1)
[-        ] process > separate_mitochondrion:GATK4_FASTQTOSAM             -
[-        ] process > separate_mitochondrion:ALIGN_RAW_READS              -
[-        ] process > separate_mitochondrion:SORT_SAM                     -
[cc/711d83] process > separate_mitochondrion:PRINT_READS (1)              [  0%] 0 of 1
[-        ] process > separate_mitochondrion:SELECT_MITO_READS            -
[-        ] process > variant_call:CALL_DEFAULT:ALIGN_MITO                -
[-        ] process > variant_call:CALL_DEFAULT:MARK_DUPLICATES           -
[-        ] process > variant_call:CALL_DEFAULT:SORT_SAM                  -
[-        ] process > variant_call:CALL_DEFAULT:COLLECT_ALIGNMENT_METRICS -
[-        ] process > variant_call:CALL_DEFAULT:COLLECT_WGS_METRICS       -
[-        ] process > variant_call:CALL_DEFAULT:CALL_MUTECT               -
[-        ] process > variant_call:CALL_SHIFTED:ALIGN_MITO                -
[-        ] process > variant_call:CALL_SHIFTED:MARK_DUPLICATES           -
[-        ] process > variant_call:CALL_SHIFTED:SORT_SAM                  -
executor >  local (1)
[-        ] process > separate_mitochondrion:GATK4_FASTQTOSAM             -
[-        ] process > separate_mitochondrion:ALIGN_RAW_READS              -
[-        ] process > separate_mitochondrion:SORT_SAM                     -
[cc/711d83] process > separate_mitochondrion:PRINT_READS (1)              [100%] 1 of 1, failed: 1 ✘
[-        ] process > separate_mitochondrion:SELECT_MITO_READS            -
[-        ] process > variant_call:CALL_DEFAULT:ALIGN_MITO                -
[-        ] process > variant_call:CALL_DEFAULT:MARK_DUPLICATES           -
[-        ] process > variant_call:CALL_DEFAULT:SORT_SAM                  -
[-        ] process > variant_call:CALL_DEFAULT:COLLECT_ALIGNMENT_METRICS -
[-        ] process > variant_call:CALL_DEFAULT:COLLECT_WGS_METRICS       -
[-        ] process > variant_call:CALL_DEFAULT:CALL_MUTECT               -
[-        ] process > variant_call:CALL_SHIFTED:ALIGN_MITO                -
[-        ] process > variant_call:CALL_SHIFTED:MARK_DUPLICATES           -
[-        ] process > variant_call:CALL_SHIFTED:SORT_SAM                  -
[-        ] process > variant_call:CALL_SHIFTED:COLLECT_ALIGNMENT_METRICS -
executor >  local (1)
[-        ] process > separate_mitochondrion:GATK4_FASTQTOSAM             -
[-        ] process > separate_mitochondrion:ALIGN_RAW_READS              -
[-        ] process > separate_mitochondrion:SORT_SAM                     -
[cc/711d83] process > separate_mitochondrion:PRINT_READS (1)              [100%] 1 of 1, failed: 1 ✘
[-        ] process > separate_mitochondrion:SELECT_MITO_READS            -
[-        ] process > variant_call:CALL_DEFAULT:ALIGN_MITO                -
[-        ] process > variant_call:CALL_DEFAULT:MARK_DUPLICATES           -
[-        ] process > variant_call:CALL_DEFAULT:SORT_SAM                  -
[-        ] process > variant_call:CALL_DEFAULT:COLLECT_ALIGNMENT_METRICS -
[-        ] process > variant_call:CALL_DEFAULT:COLLECT_WGS_METRICS       -
[-        ] process > variant_call:CALL_DEFAULT:CALL_MUTECT               -
[-        ] process > variant_call:CALL_SHIFTED:ALIGN_MITO                -
[-        ] process > variant_call:CALL_SHIFTED:MARK_DUPLICATES           -
[-        ] process > variant_call:CALL_SHIFTED:SORT_SAM                  -
[-        ] process > variant_call:CALL_SHIFTED:COLLECT_ALIGNMENT_METRICS -
[-        ] process > variant_call:CALL_SHIFTED:COLLECT_WGS_METRICS       -
[-        ] process > variant_call:CALL_SHIFTED:CALL_MUTECT               -
[-        ] process > variant_call:LIFTOVER_VCF                           -
[-        ] process > variant_call:MERGE_VCFS                             -
[-        ] process > variant_call:MERGE_STATS                            -
[-        ] process > variant_call:FILTER_MUTECT_CALLS                    -
[-        ] process > variant_call:LEFT_ALIGN_AND_TRIM_VARIANTS           -
[-        ] process > variant_call:SELECT_VARIANTS                        -
[-        ] process > variant_call:HAPLOCHECK                             -
[-        ] process > make_report:CREATE_JSON                             -
[-        ] process > make_report:AGGREGATE_SAMPLES_IN_CSV                -
Execution cancelled -- Finishing pending tasks before exit
Error executing process > 'separate_mitochondrion:PRINT_READS (1)'

Caused by:
  Process `separate_mitochondrion:PRINT_READS (1)` terminated with an error exit status (2)

Command executed:

  BAM=`find -L ./ -name "*.bam" -or -name "*.cram"`  # point to BAM, not BAI, in the gatk

  # Uses the ref.dict to infer if the mitochondrial genome is named MT or chrMT
  CHROM_NAME=`grep -q "MT" hg19.dict && echo "MT" || echo "chrM"`

  gatk PrintReads         -R hg19.fa         -L "$CHROM_NAME"         --read-filter MateOnSameContigOrNoMappedMateReadFilter         --read-filter MateUnmappedAndUnmappedReadFilter         -I $BAM         -O mito.bam

Command exit status:
  2

Command output:
  (empty)

Command error:
  Using GATK jar /usr/local/share/gatk4-4.2.5.0-0/gatk-package-4.2.5.0-local.jar
  Running:
      java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -jar /usr/local/share/gatk4-4.2.5.0-0/gatk-package-4.2.5.0-local.jar PrintReads -R hg19.fa -L chrM --read-filter MateOnSameContigOrNoMappedMateReadFilter --read-filter MateUnmappedAndUnmappedReadFilter -I ./CPM00022730_BS_DNA_J101B_12m_20220803-dragen.bam -O mito.bam
  22:18:46.608 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/usr/local/share/gatk4-4.2.5.0-0/gatk-package-4.2.5.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
  Aug 15, 2022 10:18:46 PM shaded.cloud_nio.com.google.auth.oauth2.ComputeEngineCredentials runningOnComputeEngine
  INFO: Failed to detect whether we are running on Google Compute Engine.
  22:18:46.770 INFO  PrintReads - ------------------------------------------------------------
  22:18:46.771 INFO  PrintReads - The Genome Analysis Toolkit (GATK) v4.2.5.0
  22:18:46.771 INFO  PrintReads - For support and documentation go to https://software.broadinstitute.org/gatk/
  22:18:46.771 INFO  PrintReads - Executing as ec2-user@37d4a3087459 on Linux v5.10.126-117.518.amzn2.x86_64 amd64
  22:18:46.771 INFO  PrintReads - Java runtime: OpenJDK 64-Bit Server VM v11.0.9.1-internal+0-adhoc..src
  22:18:46.771 INFO  PrintReads - Start Date/Time: August 15, 2022 at 10:18:46 PM GMT
  22:18:46.771 INFO  PrintReads - ------------------------------------------------------------
  22:18:46.772 INFO  PrintReads - ------------------------------------------------------------
  22:18:46.773 INFO  PrintReads - HTSJDK Version: 2.24.1
  22:18:46.773 INFO  PrintReads - Picard Version: 2.25.4
  22:18:46.773 INFO  PrintReads - Built for Spark Version: 2.4.5
  22:18:46.773 INFO  PrintReads - HTSJDK Defaults.COMPRESSION_LEVEL : 2
  22:18:46.773 INFO  PrintReads - HTSJDK Defaults.USE_ASYNC_IO_READ_FOR_SAMTOOLS : false
  22:18:46.773 INFO  PrintReads - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_SAMTOOLS : true
  22:18:46.774 INFO  PrintReads - HTSJDK Defaults.USE_ASYNC_IO_WRITE_FOR_TRIBBLE : false
  22:18:46.774 INFO  PrintReads - Deflater: IntelDeflater
  22:18:46.774 INFO  PrintReads - Inflater: IntelInflater
  22:18:46.774 INFO  PrintReads - GCS max retries/reopens: 20
  22:18:46.774 INFO  PrintReads - Requester pays: disabled
  22:18:46.774 INFO  PrintReads - Initializing engine
  22:18:46.826 INFO  PrintReads - Shutting down engine
  [August 15, 2022 at 10:18:46 PM GMT] org.broadinstitute.hellbender.tools.PrintReads done. Elapsed time: 0.00 minutes.
  Runtime.totalMemory()=121634816
  ***********************************************************************

  A USER ERROR has occurred: Couldn't read file file://hg19.fa. Error was: Sequence dictionary and index contain different numbers of contigs

  ***********************************************************************
  Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.

Work dir:
  /home/MITO_NF/work/cc/711d8397e91beda477218a34435894

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

**Comment by Pharmacogenetecist** [comment]
hg19.dict  hg19.fa  hg19.fa.64.alt  hg19.fa.64.amb  hg19.fa.64.ann  hg19.fa.64.bwt  hg19.fa.64.pac  hg19.fa.64.sa  hg19.fa.fai

Files are in the HG19 directory

**Comment by lmtani** [comment]
Is this reference (hg19.fa) the exact same of the one used for your alignments? I ask you because that there are some distinct versions, for example: GRCh37, hg19, hg19 + decoy sequences, etc.

**Comment by Pharmacogenetecist** [comment]
> Is this reference (hg19.fa) the exact same of the one used for your alignments? I ask you because there are some distinct versions, for example: GRCh37, hg19, hg19 + decoy sequences, etc.

Apologies for the delayed response - it is actually the hs37d5 reference, I could not find the other associated files here (https://console.cloud.google.com/storage/browser/genomics-public-data/references/hs37d5)

**Comment by lmtani** [comment]
No apologies needed.

If you can't find these files you need to create by yourself by executing:

`bwa index -6 /path/to/your/hs37d5.fa` (it will take a while)

and

`picard CreateSequenceDictionary  -R /path/to/your/hs37d5.fa` for the .dict.  (this one is fast)


I'm not sure about how to create the `.alt` file. It lists all the alt contigs present in the assembly so the aligner can properly handle it.

For the purpose of this mitochondrial workflow I think you can create an empty file.

Also, you probably have these files in the workspace you used for your alignments.

**Comment by lmtani** [comment]
I'm closing this issue. Please open it again if you need more help.
